ec-doris/kohesio-frontend

src/app/features/beneficiaries/beneficiaries.component.html, src/app/features/beneficiaries/beneficiary-detail.component.html, src/app/features/projects/project-detail.component.html, src/app/shared/models/beneficiary-detail.model.ts, src/app/shared/models/beneficiary.model.ts, src/app/shared/models/project-detail.model.ts
Closes #295, closes #301, closes #264.
=> Small bugfixes

src/app/features/projects/project-detail.component.html, src/app/shared/models/project-detail.model.ts
=> Adding link to inforegio programme #294

src/app/features/beneficiaries/beneficiaries-routing.module.ts, src/app/features/beneficiaries/beneficiary-detail.component.html, src/app/features/beneficiaries/beneficiary-detail.component.ts, src/app/features/beneficiaries/beneficiary-project-list.resolve.ts, src/app/services/beneficiary.service.ts, src/app/shared/models/beneficiary-project-list.model.ts
=> Pagination on Beneficiary Details Page

src/app/features/beneficiaries/beneficiaries.component.html, src/app/features/beneficiaries/beneficiary-detail.component.ts, src/app/features/projects/project-detail.component.html, src/app/features/projects/projects.component.ts, src/app/shared/models/filters-api.model.ts
Should fix: #300 #299 #288 #285 #277
=> Small fixes

src/app/app.component.html
=> Hid multilanguage selector from main toolbar

src/app/features/beneficiaries/beneficiary-detail.component.html, src/app/shared/models/beneficiary-detail.model.ts
=> #299 transliteration on beneficiary detail page

src/app/features/beneficiaries/beneficiary-detail.component.html
=> Aligned paginator to the right

src/app/features/home/home.component.html
=> Fixed ghost space on 1st carousel card

src/app/app.module.ts, src/app/services/config.service.ts
Appears to be fixed with this. Is this a better approach to initing modules at app start?
=> Change ConfigService setup to work in Firefox

src/app/features/home/home.component.html
=> Removed text decoration when clicking third card of the carousel

src/app/features/home/home.component.html
Refers to #239 
Refers to #341 
Refers to #345
=> Workaround for bug when clicking text on 1st card of carousel

src/app/features/beneficiaries/beneficiary-detail.component.html, src/app/features/projects/project-detail.component.html, src/app/features/projects/projects.component.html, src/app/features/projects/projects.component.scss
https://github.com/ec-doris/kohesio.eu/issues/266
=> Bug/266 Improve thumbnails

src/app/pages/static/themes/themes.component.html, src/app/pages/static/themes/themes.component.scss
=> Responsive themes page in ECL

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/components/ecl/carousel/carousel.ecl.component.html, src/app/pages/beneficiaries/beneficiaries.component.html, src/app/pages/beneficiaries/beneficiary-detail.component.html, src/app/pages/projects/project-detail.component.html, src/app/pages/projects/projects.component.html, src/app/pages/static/about/about.component.html, src/app/pages/static/privacy/privacy.component.html
=> Breadcrumbs ecl

src/app/app-routing.module.ts, src/app/app.component.ts, src/app/pages/static/themes/themes.component.html
=> Breadcrumbs ecl on Themes page

src/app/components/ecl/carousel/carousel.ecl.component.scss
=> Removing underline decoration on carousel buttons

src/app/pages/home/home.component.html, src/app/pages/home/home.component.scss
=> 401 themes component homepage

src/app/components/ecl/site-header/site-header.ecl.component.html, src/app/components/ecl/site-header/site-header.ecl.component.ts
=> Close menu on mobile menu when a page is selected

src/app/pages/projects/projects.component.ts
Probably not the most elegant solution but it should work now.
=> #477 fixing policy and themes connection

src/app/components/ecl/carousel/carousel.ecl.component.html
=> change carousel text... again

src/app/pages/projects/project-detail.component.html, src/styles.scss
=> Adding transliteration

src/app/pages/projects/projects.component.scss
=> Terms readability

angular.json, src/app/components/ecl/carousel/carousel.ecl.component.ts, src/assets/scripts/kohesio-ecl.js
=> Fixed bug on buttons and scroll when app is displayed on mobile.

src/app/models/category.model.ts
should fix issue reported by @madewild #214
=> Fix autotype not working anymore

src/app/components/kohesio/image-overlay/image-overlay.component.html, src/app/components/kohesio/image-overlay/image-overlay.component.scss
=> Changing overlay style

src/app/components/kohesio/image-overlay/image-overlay.component.html, src/app/components/kohesio/image-overlay/image-overlay.component.scss
=> 473 Adding close button to image overlay

server/src/edits/edit.service.ts, server/src/projects/project.controller.ts, server/src/queries/dtos/priorityAxis.dto.ts, server/src/queries/query.controller.ts, server/src/queries/query.service.ts, src/app/models/filters-api.model.ts, src/app/models/filters.model.ts, src/app/pages/projects/projects.component.html, src/app/pages/projects/projects.component.ts, src/app/services/translate.service.ts
priority Axis filter
language to get the edit on each project
=> new test version
